### ISSUE TITLE
Various Admin Pages not working (Local issue)

### ISSUE THREAD

**Issue by scottcwilson** [mc12345678/Stock_By_Attributes_Combined#16]
I have a Frankenversion of this plugin which I am attempting to reconcile to master.  But right now I can't see where the various SBA defines (such as the define which indicates whether to show attribute images) are set.  Please let me know where this is on the Zen menus  and which PHP file creates it so I can start debugging.

**Comment by mc12345678** [comment]
The admin/stock_by_attr_install.php file contains all of the installation "script" to identify what and where to place items in the admin menus.  With regards to the "attribute images", that was a switch added by potteryhouse and jeking to support javascript image swapping when using the SBA option name type for a product and primarily works only with single option name product.  The image is updated through the jquery in includes/functions/extra_functions/products_with_attributes.php. but the image is given an id to use as a reference to update it by the "change" of the dropdown selection.

What is this "various admin pages not working" portion of the title of this thread?

**Comment by scottcwilson** [comment]
> What is this "various admin pages not working" portion of the title of this thread?
> That's the issue I'm having which is why I can't track down that option.  What (configuration?) page is it shown on, and (if other than configuration.php) what file is run to display that data?

**Comment by mc12345678** [comment]
Configuration->Dynamic Dropdowns is added (typically just before configuration->Stock, ie. sort order 8) but is often "missed" by people reviewing the listings.
Configuration->Stock (typically gID=9) is modified to add SBA (_STOCK_ by Attributes) options.
The dropdown in catalog->option names for the option name type is modified to add SBA Select List (Dropdown) Basic.
Module "storage location" gID=6 is modified to add the constant to support that additional field.
The Configuration->Attribute settings menu (gID=13) has an added option for display of the customid to the customer.

**Comment by scottcwilson** [comment]
Thanks - I don't recall seeing Dynamic Dropdowns so perhaps that's my issue.

**Comment by mc12345678** [comment]
If it means anything, I myself still "miss" it and it didn't matter if it was at the end of the list or elsewhere and others that have installed it "don't see it" either. I chose to place it somewhere specific so that 1) if can find one of the items, the other is next to it, and 2) it seems to make sense in a controlling ZC catalog side basis. 

It may be that in the end the dynamic Dropdowns menu will be removed, but for now I wish to also honor the original developer and not force the potential short term code options into anywhere else specific. Plus, the associated code itself is still under some Flux. Maybe once it is determined to be solid, then it's "parts" can find a more appropriate home.

**Comment by scottcwilson** [comment]
Not a criticism by any means.  Like I said, the installation  which I just inherited support for has a ton of issues and I'm just fixing them one by one, so I'm trying to gather information.  Obviously the way to go for me is to install the master branch on a pristine copy of 1.5.5 and observe that; I just haven't done that yet.

**Comment by scottcwilson** [comment]
Yep, that fixed it.
