### ISSUE TITLE
missing semi-colon

### ISSUE THREAD

**Issue by proseLA** [mc12345678/Stock_By_Attributes_Combined#68]
https://github.com/mc12345678/Stock_By_Attributes_Combined/blob/bbc9346679eba4dab0cc91222da4f710270b6dbd/admin/products_with_attributes_stock.php#L759-L764

line 763 needs a `;`

**Comment by jodeantn** [comment]
I added ; to the end of line 763, however now the page does not give the error but the SBA data isn’t displayed on page?

**Comment by mc12345678** [comment]
Fixed by update to master branch with commit: affc74d62d3d5f358ea89ecd57b8f2915d353373
Semi-colon was missed by local addition of comment characters the left the semi-colon, but the line  (having just commented out code and a semi-colon) was not carried over in updating github.

Anyways that is now corrected in github. Closing this.
